# Generated by Django 5.2.7 on 2025-11-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_coach",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_player",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("player", "Player"),
                    ("coach", "Coach"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="player",
                max_length=20,
            ),
        ),
    ]
