# Generated by Django 5.2.7 on 2025-11-03 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", models.CharField(blank=True, max_length=120, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.coach"
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sport",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start",
                    models.DateField(help_text="Start of ISO week (Monday)"),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_scores",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "unique_together": {("player", "week_start")},
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=True)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional per-session rating by coach"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attendances",
                        to="core.player",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="core.coachingsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "player")},
            },
        ),
    ]
