# Generated by Django 5.2.7 on 2025-11-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_coachingsession_performancescore_sessionattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sport",
            ),
        ),
    ]
